# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: wstunnel

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - id: linux-x86_64
    builder: rust
    flags:
      - --release
      - --package=wstunnel-cli
      - --features=jemalloc
    targets:
      - x86_64-unknown-linux-musl

  - id: linux-aarch64
    builder: rust
    flags:
      - --release
      - --package=wstunnel-cli
      - --features=jemalloc
    targets:
      - aarch64-unknown-linux-musl
    env:
      - JEMALLOC_SYS_WITH_LG_PAGE=14

  - id: linux-i686
    builder: rust
    flags:
      - --release
      - --package=wstunnel-cli
      - --features=aws-lc-rs-bindgen
    targets:
      - i686-unknown-linux-musl

  - id: linux-arm
    builder: rust
    flags:
      - --release
      - --package=wstunnel-cli
      - --no-default-features
      - --features=ring
    targets:
      - armv7-unknown-linux-musleabihf
      - arm-unknown-linux-musleabihf

archives:
  - id: linux-archives
    formats: [ "tar.gz" ]

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    formats:
      - deb
      - apk
      - rpm
    vendor: erebe
    homepage: https://github.com/erebe/wstunnel
    maintainer: erebe
    description: "Tunneling over WebSocket - Bypass firewalls and proxies"
    license: BSD-3-Clause
    section: net

checksum:
  name_template: "checksums-linux.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

sboms:
  - artifacts: archive

source:
  enabled: true
