version: 2

before:
  hooks:
    - rustup toolchain install 1.90
    - rustup default 1.90

builds:
  - id: linux-musl
    builder: rust
    # dir: wstunnel-cli
    binary: wstunnel
    tool: cross
    command: build
    flags:
      - --release
      - --package=wstunnel-cli
      - --features=jemalloc
    targets:
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-musl

  - id: linux-gnu
    builder: rust
    # dir: wstunnel-cli
    binary: wstunnel
    tool: cross
    command: build
    flags:
      - --release
      - --package=wstunnel-cli
      - --features=jemalloc
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu

  - id: macos
    builder: rust
    binary: wstunnel
    tool: cargo
    command: build
    flags:
      - --release
      - --package=wstunnel-cli
      # - --features=jemalloc # jemalloc issue on macos with cross-compilation/goreleaser environment
    targets:
      - x86_64-apple-darwin
      - aarch64-apple-darwin
    env:
      - CFLAGS=
      - LDFLAGS=
      - CC=
      - CXX=


  - id: linux-arm-v7-gnu
    builder: rust
    # dir: wstunnel-cli
    binary: wstunnel
    tool: cross
    command: build
    flags:
      - --release
      - --package=wstunnel-cli
      - --no-default-features
      - --features=ring
    targets:
      - armv7-unknown-linux-gnueabihf

      
  - id: freebsd-x64
    builder: rust
    # dir: wstunnel-cli
    binary: wstunnel
    tool: cross
    command: build
    flags:
      - --release
      - --package=wstunnel-cli
      - --no-default-features
      - --features=ring,jemalloc
    targets:
      - x86_64-unknown-freebsd

  - id: windows
    builder: rust
    # dir: wstunnel-cli
    binary: wstunnel
    tool: cross
    command: build
    flags:
      - --profile=release-with-symbols
    targets:
      - x86_64-pc-windows-msvc

archives:
  - id: default
    ids:
      - macos
      - linux-gnu
      - linux-musl
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end }}
      {{- if contains .Target "musl" }}-musl{{ end }}
      {{- if contains .Target "gnu" }}-gnu{{ end }}


checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: wstunnel
    package_name: wstunnel
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: erebe
    homepage: https://github.com/erebe/wstunnel
    maintainer: erebe
    description: "Tunneling over WebSocket - Bypass firewalls and proxies"
    license: BSD-3-Clause
    formats:
      - deb
      - rpm
    ids:
      - linux-gnu
    section: net
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/wstunnel/copyright
      - src: ./README.md
        dst: /usr/share/doc/wstunnel/README.md

release:
  replace_existing_artifacts: true
  prerelease: auto
