# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: wstunnel

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - id: freebsd-x86_64
    builder: rust
    binary: wstunnel
    goos:
      - freebsd
    goarch:
      - amd64
    flags:
      - --release
      - --package=wstunnel-cli
      - --no-default-features
      - --features=ring
      - --features=jemalloc

  - id: freebsd-i686
    builder: rust
    binary: wstunnel
    goos:
      - freebsd
    goarch:
      - "386"
    flags:
      - --release
      - --package=wstunnel-cli
      - --no-default-features
      - --features=ring

archives:
  - id: freebsd-archives
    formats: [ "tar.gz" ]

checksum:
  name_template: "checksums-freebsd.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

sboms:
  - artifacts: archive

source:
  enabled: false
